-- HappyTrip: core schema (destinations, tours, reviews, blog posts, bookings, profiles)
-- Run once in the Supabase Dashboard -> SQL Editor -> New query -> Run.
--
-- NOT YET CONNECTED to the site. The current site reads/writes its data locally
-- (data.js for seed content, store.js for localStorage). This schema is a
-- drop-in target for whenever the site is wired up to a real Supabase project —
-- table and field names intentionally mirror data.js's shape so that migration
-- is closer to a data export than a rewrite.

-- ---------- Destinations ----------
drop table if exists public.destinations cascade;

create table public.destinations (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  region text,
  tagline text,
  description text,
  best_time text,
  climate text,
  highlights text[] not null default '{}',
  tips text[] not null default '{}',
  theme text,
  icon text,
  created_at timestamptz not null default now()
);

alter table public.destinations enable row level security;

create policy "Public read access" on public.destinations for select using (true);
create policy "Public insert access" on public.destinations for insert with check (true);
create policy "Public update access" on public.destinations for update using (true) with check (true);
create policy "Public delete access" on public.destinations for delete using (true);

-- ---------- Tours ----------
drop table if exists public.tours cascade;

create table public.tours (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  destination_id bigint references public.destinations(id) on delete set null,
  type text,
  type_label text,
  duration_days int not null default 1,
  difficulty text,
  difficulty_label text,
  group_min int not null default 1,
  group_max int not null default 10,
  price_basic numeric not null default 0,
  price_standard numeric not null default 0,
  price_premium numeric not null default 0,
  discount int not null default 0,
  summary text,
  inclusions text[] not null default '{}',
  exclusions text[] not null default '{}',
  meeting_point text,
  languages text[] not null default '{}',
  itinerary jsonb not null default '[]'::jsonb,
  images text[] not null default '{}',
  theme text,
  icon text,
  featured boolean not null default false,
  rating numeric not null default 5.0,
  review_count int not null default 0,
  created_at timestamptz not null default now()
);

alter table public.tours enable row level security;

create policy "Public read access" on public.tours for select using (true);
create policy "Public insert access" on public.tours for insert with check (true);
create policy "Public update access" on public.tours for update using (true) with check (true);
create policy "Public delete access" on public.tours for delete using (true);

-- ---------- Reviews ----------
drop table if exists public.reviews cascade;

create table public.reviews (
  id bigint generated by default as identity primary key,
  tour_id bigint references public.tours(id) on delete cascade,
  name text not null,
  rating int not null check (rating between 1 and 5),
  text text,
  verified boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

create policy "Public read access" on public.reviews for select using (true);
create policy "Public insert access" on public.reviews for insert with check (true);

-- ---------- Blog posts ----------
drop table if exists public.blog_posts cascade;

create table public.blog_posts (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  category text,
  author text,
  excerpt text,
  content text[] not null default '{}',
  theme text,
  icon text,
  read_minutes int not null default 5,
  published_at date not null default current_date
);

alter table public.blog_posts enable row level security;

create policy "Public read access" on public.blog_posts for select using (true);
create policy "Public insert access" on public.blog_posts for insert with check (true);
create policy "Public update access" on public.blog_posts for update using (true) with check (true);

-- ---------- Profiles (one row per authenticated user) ----------
drop table if exists public.profiles cascade;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  theme text not null default 'light',
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "Users read own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users insert own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

-- ---------- Bookings (scoped to the owning user, unlike the public catalog tables) ----------
drop table if exists public.bookings cascade;

create table public.bookings (
  id bigint generated by default as identity primary key,
  reference text unique not null,
  user_id uuid references auth.users(id) on delete set null,
  tour_id bigint references public.tours(id) on delete set null,
  tour_title text,
  tier text,
  travelers int not null default 1,
  travel_date date,
  contact_name text,
  contact_email text,
  contact_phone text,
  traveler_names text[] not null default '{}',
  special_requests text,
  extras jsonb not null default '{}'::jsonb,
  total numeric not null default 0,
  status text not null default 'დადასტურებული',
  created_at timestamptz not null default now()
);

alter table public.bookings enable row level security;

create policy "Users read own bookings" on public.bookings for select using (auth.uid() = user_id);
create policy "Users insert own bookings" on public.bookings for insert with check (auth.uid() = user_id);
create policy "Users update own bookings" on public.bookings for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- admin.html stays client-gated only for now (same tradeoff goodmotoway's admin panel
-- makes). A future upgrade could add an `is_admin` flag on profiles and require it
-- in the tours/destinations write policies above instead of leaving them fully public.

-- ---------- Storage bucket for future tour/destination photos ----------
insert into storage.buckets (id, name, public)
values ('happytrip-images', 'happytrip-images', true)
on conflict (id) do nothing;

drop policy if exists "Public read happytrip images" on storage.objects;
drop policy if exists "Public upload happytrip images" on storage.objects;
drop policy if exists "Public delete happytrip images" on storage.objects;

create policy "Public read happytrip images" on storage.objects
  for select using (bucket_id = 'happytrip-images');

create policy "Public upload happytrip images" on storage.objects
  for insert with check (bucket_id = 'happytrip-images');

create policy "Public delete happytrip images" on storage.objects
  for delete using (bucket_id = 'happytrip-images');
